In [57]:
import numpy

In [2]:
numpy.__version__


'1.13.3'

In [1]:
import numpy as np

# Python list 的特点

In [4]:
L=[i for i in range(10)]

In [5]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
L[5]=100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [7]:
L[5]='kang'
L

[0, 1, 2, 3, 4, 'kang', 6, 7, 8, 9]

In [8]:
import array

In [9]:
arr =array.array('i',[i for i in range(10)])
arr            #i 代表整形

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[5]='kang'

TypeError: an integer is required (got type str)

# numpy.array

In [ ]:
nparry = np.array([i for i in range(10)])
nparry

In [ ]:
nparry[5]

In [ ]:
nparry.dtype

In [ ]:
nparry[5] = 5.0

In [ ]:
nparry

In [ ]:
nparry.dtype

In [ ]:
nparr2 = np.array([1,2,3.0,4])
nparr2

In [ ]:
nparr2.dtype

# 其他创建numpy.array的方法

In [ ]:
np.zeros(10)

In [ ]:
np.zeros(10).dtype

In [ ]:
np.zeros(10,dtype=int)

In [ ]:
np.zeros(shape=(3,5),dtype=int)

In [ ]:
np.ones(shape=(3,5),dtype=int)

In [12]:
a=np.full((3,5),fill_value=666)               #指定的数字的矩阵

In [13]:
a[1,2]=55
a

array([[666, 666, 666, 666, 666],
       [666, 666,  55, 666, 666],
       [666, 666, 666, 666, 666]])

# arange

In [14]:
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [15]:
[i for i in range(0,1,0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [16]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
np.arange(0,1,0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## linspace


In [20]:
np.linspace(0,20,5)        #在0到20之间等长的截出10个点     包含0到20

array([  0.,   5.,  10.,  15.,  20.])

In [21]:
np.linspace(0,20,11)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.])

# 随机数     random

In [2]:
np.random.randint(0,10)

8

In [3]:
np.random.randint(0,10,10)             #前闭后开

array([4, 0, 5, 6, 0, 6, 9, 2, 3, 7])

In [4]:
np.random.randint(4,8,size=10)

array([7, 5, 4, 6, 6, 6, 4, 5, 5, 7])

In [5]:
np.random.randint(1,10,size=(3,5))             #1-10之间  3行5列

array([[9, 9, 3, 7, 4],
       [8, 2, 6, 3, 8],
       [1, 5, 9, 4, 2]])

In [6]:
np.random.randint(1,10,size=(3,5))

array([[6, 2, 3, 6, 1],
       [5, 7, 9, 8, 1],
       [4, 8, 1, 3, 2]])

In [7]:
np.random.seed(666)         #随机种子

In [42]:
np.random.randint(1,10,size=(3,5))

array([[9, 2, 1, 9, 3],
       [7, 6, 8, 3, 5],
       [3, 1, 5, 2, 1]])

In [47]:
np.random.seed(666)
np.random.randint(1,10,size=(3,5))

array([[3, 7, 5, 4, 2],
       [1, 9, 8, 6, 3],
       [6, 6, 5, 9, 5]])

In [ ]:
np.random.seed(666)
np.random.randint(1,10,size=(3,5))

In [48]:
np.random.random()

0.11285765363170797

In [49]:
np.random.random(10)

array([ 0.11095367,  0.24766823,  0.0232363 ,  0.72732115,  0.34003494,
        0.19750316,  0.90917959,  0.97834699,  0.53280254,  0.25913185])

In [50]:
np.random.random((3,5))

array([[ 0.58381262,  0.32569065,  0.88889931,  0.62640453,  0.81887369],
       [ 0.54734542,  0.41671201,  0.74304719,  0.36959638,  0.07516654],
       [ 0.77519298,  0.21940924,  0.07934213,  0.48678052,  0.1536739 ]])

In [51]:
np.random.normal()             #均值为0 方差为1

-0.441182436639169

In [61]:
np.random.normal(10,100)             #均值为10，方差为100

-13.276003531407824

In [ ]:
np.random.normal(0,1,(3,5))  

In [ ]:
np.random.normal?             #查询这个函数的用法

In [ ]:
np.random?

In [ ]:
help(np.random)

In [65]:
a =np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a[::2]

array([0, 2, 4, 6, 8])