In [2]:
import numpy as np

In [4]:
x = np.arange(10)
x.shape

(10,)

In [5]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# 基本属性

In [6]:
X.ndim               #返回是几维

2

In [11]:
x.ndim

1

In [12]:
x.shape

(10,)

In [13]:
X.shape

(3, 5)

In [14]:
x.size

10

In [15]:
X.size

15

# numpy.array 的数据访问

In [16]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x[0]

0

In [18]:
x[-1 ]

9

In [19]:
X[0][0]

0

In [24]:
X[:,0]           #访问多维数组的方法

array([ 0,  5, 10])

In [8]:
x[0:5]

array([0, 1, 2, 3, 4])

In [25]:
x[:5]

array([0, 1, 2, 3, 4])

In [26]:
x[::2]      #步长为2

array([0, 2, 4, 6, 8])

In [27]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [30]:
X[:2,:3]         #前两行前3列

array([[0, 1, 2],
       [5, 6, 7]])

In [31]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [37]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [39]:
X[::-1,]

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [10]:
X[:,0].ndim

1

In [42]:
subx = X[:2,:3]
subx

array([[0, 1, 2],
       [5, 6, 7]])

In [44]:
subx[0,0]=100
subx

array([[100,   1,   2],
       [  5,   6,   7]])

In [45]:
X           #修改子矩阵会改变原矩阵    修改原矩阵也会改变子矩阵

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [ ]:
#如果不想改变

In [46]:
suby = X[:2,:3].copy()

In [47]:
suby

array([[100,   1,   2],
       [  5,   6,   7]])

In [48]:
suby[0,0]=0

In [49]:
suby

array([[0, 1, 2],
       [5, 6, 7]])

In [50]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

# Reshape

In [51]:
x.shape

(10,)

In [52]:
x.ndim

1

In [54]:
x.reshape(2,5)                   #没有改变x自身

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
A=x.reshape(2,5)

In [56]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [58]:
x.reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# 合并与分割

In [59]:
x=np.array([1,2,3])
y=np.array([3,2,1])

In [61]:
np.concatenate([x,y])      #元素的合并   注意其中是一个【】

array([1, 2, 3, 3, 2, 1])

In [62]:
z = np.array([666,666,666])

In [63]:
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [64]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [65]:
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [69]:
np.concatenate([A,A],axis=1)        #沿着不同的方向进行拼接   0  行  1  列

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [72]:
c=np.concatenate([A,z.reshape(-1,3)])

In [73]:
c

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [74]:
np.vstack([A,z])                #更加智能   垂直拼接     

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [82]:
B = np.full((3,2),100)

In [83]:
B

array([[100, 100],
       [100, 100],
       [100, 100]])

In [84]:
np.hstack([c,B])                   #水平拼接

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100],
       [666, 666, 666, 100, 100]])

# 分割操作

In [86]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
x1,x2,x3 = np.split(x,[3,7])         #切割    不包括3  7

In [88]:
x1

array([0, 1, 2])

In [89]:
x2

array([3, 4, 5, 6])

In [91]:
x3

array([7, 8, 9])

In [92]:
np.split(x,[5])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [93]:
A = np.arange(16).reshape((4,4))

In [94]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [99]:
np.split(A,[2])                 #二维数组 默认按行分割

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [100]:
np.split(A,[2],axis=1)      #按列分割

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [101]:
np.vsplit(A,[2])               #处置进行分割

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [102]:
np.hsplit(A,[2])                  #水平进行分割

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [103]:
x,y=np.hsplit(A,[-1])

In [104]:
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [105]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [110]:
A[:,-1]

array([ 3,  7, 11, 15])