# 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()           #获取到我们的数据集

In [3]:
x = iris.data      #将4中数据放入X
y = iris.target    #将花的类型放入y

In [15]:
x.shape

(150, 4)

In [5]:
y.shape

(150,)

# 开始数据分离     train_test_split    将测试数据和训练数据分离

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
#只对索引进行打乱
# len(x)    为了不失一般性
shuffle_indexes = np.random.permutation(len(x))    #将下标进行打乱
shuffle_indexes

array([  1, 148, 137,  11,  88, 129, 146, 127,  85, 134, 115,  20,  33,
        53, 106, 102, 124,  36,  57,  93,  48,  68,  12, 147, 139,  76,
        58,  28,  10,  66,  44,  90,  54, 141, 140,  23,  99,  41,   0,
        65,  51,  29, 125,  22,   9, 119, 114,  87,  91, 108, 128,  16,
        30,  25,  62,  81,  45, 122, 101,  32,  67,  69,  15,  19, 107,
        71,  50, 121, 145,  77,  72,  96, 112,  70, 104,  31,   5,  95,
        27, 131,  39, 144, 126, 149,  97,  46,   7, 118,  98,  37,  86,
        59,  94,   8,   3,  43,   6,  73, 103, 113,  63,  84,  26, 136,
        56,  14,  89,   2,  92,  17, 123,  38, 138,  24,  55,  35,  42,
       109, 105,  78, 120,  13, 111,  18, 100,  74,  75, 135,  47,   4,
        64, 117,  61,  34, 132,  60,  52, 133,  80, 110,  82, 142,  49,
       130,  40,  79, 143,  83,  21, 116])

In [8]:
test_ratio = 0.2   #测试数据集
test_size =int(len(x)*test_ratio)     #我们测试数据集的大小
test_size

30

In [9]:
test_indexes = shuffle_indexes[:test_size]
train_indexes =  shuffle_indexes[test_size: ]     #我们将前20%当做测试  后80%当做训练

In [10]:
#然后我们取出相应的数据
x_train = x[train_indexes]
y_train = y[train_indexes]

x_test = x[test_indexes]
y_test = y[test_indexes]

In [12]:
print(x_train.shape)

(120, 4)


# 此时用我们自己写的代码来重新进行一次上述的

In [24]:
%run D:/Python1/KNN/model_selection.py

In [25]:
X_train,y_train,X_test,y_test = train_test_split(x,y)

In [26]:
X_train.shape

(120, 4)

In [27]:
%run D:/Python1/KNN/KNeighbor_Class.py

In [29]:
my_knn = KNN(k=3)

In [30]:
my_knn.fit(X_train=X_train,Y_train=y_train)

KNN(K=3)

In [35]:
a = my_knn.predit(X_test)
a

array([1, 0, 2, 1, 2, 2, 2, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 2, 0, 0, 1, 1, 2,
       1, 0, 0, 1, 2, 0, 2])

In [32]:
y_test

array([1, 0, 2, 1, 2, 2, 2, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 2,
       1, 0, 0, 1, 2, 0, 2])

In [34]:
np.sum(a==y_test)

29

In [36]:
np.sum(a==y_test)/len(y_test)        #准确度

0.96666666666666667

# Sklearn中的train_test_split

In [61]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [59]:
 X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=666)

In [60]:
X_train.shape

(120, 4)

In [62]:
knn1 = KNeighborsClassifier(n_neighbors=3)

In [63]:
knn1.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [64]:
knn1.predict(X_test)

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0, 2,
       0, 1, 1, 0, 1, 2, 2])

In [66]:
y_test

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0, 2,
       0, 1, 1, 0, 1, 2, 2])

In [67]:
np.sum(knn1.predict(X_test)==y_test)

30