In [20]:
import tensorflow as tf

In [21]:
a = tf.Variable(tf.random_normal([10]))
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    print(sess.run(a))

[1.6929938  1.1269828  0.9770396  0.85557055 1.2096452  0.3169148
 0.4585903  2.258506   0.91671443 0.06770381]


In [7]:
import numpy as np
import tensorflow as tf
data = np.array([[[2],[1]],[[3],[4]],[[6],[7]]])
data = tf.convert_to_tensor(data)
lk = [[0,1],[1,0],[0,0]]
lookup_data = tf.nn.embedding_lookup(data,lk)
init = tf.global_variables_initializer()


In [8]:
print(data.shape) 
print(np.array(lk).shape)

print(lookup_data)

(3, 2, 1)
(3, 2)
Tensor("embedding_lookup_2/Identity:0", shape=(3, 2, 2, 1), dtype=int32)


In [9]:
data

<tf.Tensor 'Const_1:0' shape=(3, 2, 1) dtype=int32>

In [10]:
lk

[[0, 1], [1, 0], [0, 0]]

In [11]:
params=np.random.normal(loc=0.0,scale=1.0,size=[10,10])

ids=[1,2,3]

with tf.Session() as sess:
    print(sess.run(tf.nn.embedding_lookup(params,ids)))

[[ 1.01009567 -0.09468275 -2.10134052 -0.11244748 -0.07686935  0.94705529
   0.3819986   0.65501114 -1.23198403  1.72992367]
 [-0.77738796  1.15738061  0.52007168 -2.15401544 -1.21244142  1.20048699
  -2.09589276  0.00248601 -0.41389429 -0.70342575]
 [ 0.06463637  0.95685355  0.65676932 -0.78421206  0.01330114 -1.5730424
  -1.31841763  0.47591283  0.1067817   0.66221629]]


In [12]:
params

array([[-1.49832031e-01, -1.09685072e+00, -3.22074029e-01,
         1.87938511e-01, -3.90136069e-01, -1.04814008e+00,
         6.60281656e-01,  5.05004583e-01,  1.23787228e-01,
        -3.49191461e-01],
       [ 1.01009567e+00, -9.46827464e-02, -2.10134052e+00,
        -1.12447482e-01, -7.68693518e-02,  9.47055293e-01,
         3.81998596e-01,  6.55011144e-01, -1.23198403e+00,
         1.72992367e+00],
       [-7.77387963e-01,  1.15738061e+00,  5.20071682e-01,
        -2.15401544e+00, -1.21244142e+00,  1.20048699e+00,
        -2.09589276e+00,  2.48600584e-03, -4.13894288e-01,
        -7.03425747e-01],
       [ 6.46363731e-02,  9.56853548e-01,  6.56769316e-01,
        -7.84212056e-01,  1.33011376e-02, -1.57304240e+00,
        -1.31841763e+00,  4.75912826e-01,  1.06781700e-01,
         6.62216289e-01],
       [ 9.62112454e-03, -1.57731256e+00, -2.09260586e+00,
         9.97143356e-01, -1.35515763e+00,  3.10053322e-01,
        -7.70412564e-01,  4.90983359e-01, -2.11574668e-01,
        -9.

In [13]:
# 创建一个常量 Operation(操作)
hw = tf.constant('hello world !i love TensorFlow')

In [14]:
# 启动 一个TensorFlow 的Session会话
sess = tf.Session()

In [15]:
# 运行Graph 图计算
print(sess.run(hw))

b'hello world !i love TensorFlow'


In [8]:
sess.close()

In [16]:
import numpy as np

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
const = tf.constant(3)

In [13]:
const

<tf.Tensor 'Const_1:0' shape=() dtype=int32>

In [14]:
tf.Session().run(const)

3

In [15]:
# 常量
tensor = tf.constant([1, 2, 3, 4, 5, 6, 7])

In [16]:
tf.Session().run(tensor)

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
# 变量
var = tf.Variable(3)

In [19]:
var

<tf.Variable 'Variable:0' shape=() dtype=int32_ref>

In [20]:
var1 = tf.Variable(4,dtype=tf.int64)
var1

<tf.Variable 'Variable_1:0' shape=() dtype=int64_ref>

In [23]:
# Placeholder（占位符） 先占住一个位置，等着你之后往里面添加值
x = tf.placeholder(tf.float32, shape=(1024, 1024))
y = tf.matmul(x, x)

with tf.Session() as sess:
  rand_array = np.random.rand(1024, 1024)
  print(sess.run(y, feed_dict={x: rand_array}))  # Will succeed.

[[261.94998 258.62372 259.9097  ... 257.72586 258.94333 269.64487]
 [268.47757 262.8418  260.86526 ... 261.43146 272.40347 269.92282]
 [263.20956 259.55865 259.0498  ... 255.62231 264.1982  270.52414]
 ...
 [260.52496 258.7315  258.57114 ... 251.67383 262.50864 264.9181 ]
 [257.37198 254.21161 252.81706 ... 247.91136 258.0006  260.52777]
 [265.60907 261.09442 253.59164 ... 249.21143 260.55103 263.31018]]


In [35]:
# SparseTensor(稀疏张量)  类似于线性代数里的稀疏矩阵概念
sparse = tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
sparse

In [42]:
# Tensor 的表示法
var2 = tf.Variable([3,4])
var2

<tf.Variable 'Variable_6:0' shape=(2,) dtype=int32_ref>

In [43]:
var3 = tf.Variable([3,4],[5,6])
var3

<tf.Variable 'Variable_7:0' shape=(2,) dtype=int32_ref>

In [46]:
var4 = tf.Variable([4,6],name='varname_var')
var4

<tf.Variable 'varname_var:0' shape=(2,) dtype=int32_ref>

In [48]:
const = tf.constant(3)
const

<tf.Tensor 'Const_4:0' shape=() dtype=int32>

In [49]:
const1 = tf.constant(3)
const1

<tf.Tensor 'Const_5:0' shape=() dtype=int32>

In [50]:
const1 = tf.constant(3,name='cons_con')
const1

<tf.Tensor 'cons_con:0' shape=() dtype=int32>

In [52]:
conn = tf.constant([[2,3],[4,5]],name='con_1',dtype=tf.int64)

In [53]:
conn

<tf.Tensor 'con_1_1:0' shape=(2, 2) dtype=int64>

In [54]:
sess = tf.Session() # 创建会话
sess

In [55]:
sess.run(conn)

array([[2, 3],
       [4, 5]], dtype=int64)

In [58]:
# 获取图
if conn.graph is tf.get_default_graph():
    print("The Graph of conn is  the default graph of the context")

The Graph of conn is  the default graph of the context


In [60]:
import tensorflow as tf

In [62]:
a = 3 

# 创建变量
w = tf.Variable([[0.5,1.0]])
x = tf.Variable([[2.0],[1.0]])
y = tf.matmul(w,x)
print(y)

Tensor("MatMul_2:0", shape=(1, 1), dtype=float32)


In [65]:
# 进行初始化
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(y))
    print(y)
    print(y.eval())

[[2.]]
Tensor("MatMul_2:0", shape=(1, 1), dtype=float32)
[[2.]]


### 基本方法

In [70]:
a = tf.zeros([3,4],dtype=tf.int32)
with tf.Session() as sess:
    print(a.eval())   

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [74]:
ten = tf.Variable([[1,2,3],[4,5,6]])
with tf.Session() as sess:
   print( tf.ones_like(ten).eval())
   print(tf.zeros_like(ten).eval())

[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]


In [75]:
a = tf.ones([3,4],dtype=tf.int32)
with tf.Session() as sess:
    print(a.eval())  

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [78]:
con = tf.constant([1,2,3,4,5,6])
with tf.Session() as sess:
    print(sess.run(con))  

[1 2 3 4 5 6]


In [79]:
con1 = tf.constant(-1.0,shape=[2,3])
with tf.Session() as sess:
    print(sess.run(con1))

[[-1. -1. -1.]
 [-1. -1. -1.]]


In [95]:
lins = tf.linspace(10.0,19.0,3,name='linspace_a_1')
with tf.Session() as sess:
    print(sess.run(lins))

[10.  14.5 19. ]


In [97]:
with tf.Session() as sess:
    print(sess.run(tf.range(3,18,3)))
# 每3个一加

[ 3  6  9 12 15]


In [98]:
# 随机值 正态分布
norm = tf.random_normal([2,3],mean=-1,stddev=4)
with tf.Session() as sess:
    print(sess.run(norm))

[[ 0.7010944 -2.9229321 -1.9312294]
 [ 1.7709048  1.5539069  4.7294865]]


In [115]:
s = tf.constant([[1,2],[3,4],[5,6]])
shuff = tf.random_shuffle(s)
with tf.Session() as sess:
    print(sess.run(shuff))

[[3 4]
 [1 2]
 [5 6]]


In [119]:
# 让当前的值进行+1的操作
state = tf.Variable(0)
new_value = tf.add(state,tf.constant(1))
updata = tf.assign(state,new_value)  # 将后面的值赋值给前一个值
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(state))
    for i in range(3):
        sess.run(updata)
        print(sess.run(state))

0
1
2
3


In [135]:
# tf.train.Saver
# 创建变量
w = tf.Variable([[0.5,1.0]])
x = tf.Variable([[2.0],[1.0]])
y = tf.matmul(w,x)
# 添加用于初始化变量的节点
init_op = tf.global_variables_initializer()
# 添加用于保存和加载所有变量的节点
saver = tf.train.Saver()
# 然后，加载模型，初始化所有变量，完成一些操作后，把变量保存到磁盘上
with tf.Session() as sess:
    sess.run(init_op)
    # 将变量保存到磁盘上
    save_path = saver.save(sess, "D://jupyter-notebook-code//Tensorflow//a.ckpt")
    print("Model saved in file: %s" %save_path)

Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
[5, 6] has type list, but expected one of: int, long, bool
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
[5, 6] has type list, but expected one of: int, long, bool
Model saved in file: D://jupyter-notebook-code//Tensorflow//a.ckpt


In [140]:
import numpy as np
a = np.zeros([3,3])
#将numpy装换为tensor
ta = tf.convert_to_tensor(a)
with tf.Session() as sess:
    print(sess.run(ta))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [141]:
# Placeholder（占位符） 先占住一个位置，等着你之后往里面添加值
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)
output = tf.multiply(input1,input2)
with tf.Session() as sess:
    print(sess.run(output,feed_dict={input1:[7.],input2:[8.]}))

[56.]


In [16]:

import tensorflow as tf;  
import numpy as np;  
import matplotlib.pyplot as plt;  
  
a1 = tf.get_variable(name='a4', shape=[2,3])
# a2 = tf.get_variable(name='a2', shape=[1], tf.constant(1))
# a3 = tf.get_variable(name='a3', shape=[2,3], tf.ones())
 
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print (sess.run(a1))
#     print (sess.run(a2))


    

[[0.19765818 0.43013275 1.0513399 ]
 [0.75510454 0.21201646 0.09653997]]


In [28]:
# 累加

x = tf.Variable(0,dtype=tf.float32,name='v_x')
# x = x+1
assign_op= tf.assign(ref=x,value=x+1)
b = tf.add(x,1)
init = tf.global_variables_initializer()

In [27]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(b))
    for i in range(5):
        print(sess.run(assign_op))
        print('x:{}'.format(sess.run(x)))
       
    

1.0
1.0
x:1.0
2.0
x:2.0
3.0
x:3.0
4.0
x:4.0
5.0
x:5.0


In [39]:
# 阶乘
# 定义不定形状的变量
x = tf.Variable(initial_value=[],dtype=tf.float32,trainable=False,validate_shape=False)   # 不定形状, 第二个设置为true的话，在变量进行更新的时候，进行shape检查默认为true
# 变量更改
concat = tf.concat([x,[0.0,0.0]],axis=0)
ass = tf.assign(x,concat,validate_shape=False)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for i in range(5):
        print(sess.run(ass))

[0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [58]:
# 阶乘
# 定义一个变量  一个占位符
sum = tf.Variable(1,dtype=tf.float32)
i = tf.placeholder(dtype=tf.float32)
tup_sum = sum*i
ass = tf.assign(sum,tup_sum)
init = tf.global_variables_initializer()
# with tf.Session() as sess:
#     sess.run(init)
#     for j in range(1,6):
#         sess.run(ass,feed_dict={i:j})
#         print(sess.run(sum))

In [59]:
print(list(range(1,5)))

[1, 2, 3, 4]


In [60]:
with tf.control_dependencies([ass]):
    # 如果想执行代码块内的内容必须先执行control_dependencies中的内容
    sum = tf.Print(sum,data=[sum,sum.read_value()],message='sum')

In [72]:


with tf.Session(config=(tf.ConfigProto(log_device_placement=True,allow_soft_placement=True))) as sess:
    sess.run(init)
    for j in range(1,6):
#         control_dependencies可以指定依赖关系 这样就不用管更新操作
        r = sess.run(sum,feed_dict={i:j})
    print(r)

120.0


In [18]:
%ls

 驱动器 D 中的卷是 软件
 卷的序列号是 0009-0369

 D:\jupyter-notebook-code\Tensorflow 的目录

2018/11/12 周一  10:57    <DIR>          .
2018/11/12 周一  10:57    <DIR>          ..
2018/10/26 周五  19:15    <DIR>          .ipynb_checkpoints
2018/10/18 周四  14:01    <DIR>          __pycache__
2018/10/24 周三  15:45             4,339 0.简单的实现神经网络.ipynb
2018/11/12 周一  10:57            29,042 1.HelloWorld.ipynb
2018/10/29 周一  17:18            25,528 10.Tensorflow实现卷积神经网络.ipynb
2018/10/25 周四  15:00            31,712 11.保存训练完的网络.ipynb
2018/10/27 周六  17:37             9,203 12.保存训练完的CNN.ipynb
2018/10/25 周四  17:25               628 13.VGG.ipynb
2018/10/29 周一  10:16             8,812 14.Tensorflow实现RNN.ipynb
2018/10/27 周六  16:03             3,188 2.一个完整的程序.ipynb
2018/11/01 周四  14:55             4,281 3.TensorBoard练习.ipynb
2018/10/18 周四  11:34            45,507 4.Tensorflow实现梯度下降.ipynb
2018/10/18 周四  10:09            24,088 5.激活函数的使用.ipynb
2018/10/18 周四  11:34            38,207 6.实现线性回归.ipynb
2018/10/27 周六  16:10          

P(A∣B)=P(B∣A),P(A)P(B)