In [4]:
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

In [5]:
boston = datasets.load_boston()

In [6]:
boston.keys()

dict_keys(['DESCR', 'feature_names', 'target', 'data'])

In [24]:
boston.data

array([[  6.32000000e-03,   1.80000000e+01,   2.31000000e+00, ...,
          1.53000000e+01,   3.96900000e+02,   4.98000000e+00],
       [  2.73100000e-02,   0.00000000e+00,   7.07000000e+00, ...,
          1.78000000e+01,   3.96900000e+02,   9.14000000e+00],
       [  2.72900000e-02,   0.00000000e+00,   7.07000000e+00, ...,
          1.78000000e+01,   3.92830000e+02,   4.03000000e+00],
       ..., 
       [  6.07600000e-02,   0.00000000e+00,   1.19300000e+01, ...,
          2.10000000e+01,   3.96900000e+02,   5.64000000e+00],
       [  1.09590000e-01,   0.00000000e+00,   1.19300000e+01, ...,
          2.10000000e+01,   3.93450000e+02,   6.48000000e+00],
       [  4.74100000e-02,   0.00000000e+00,   1.19300000e+01, ...,
          2.10000000e+01,   3.96900000e+02,   7.88000000e+00]])

In [18]:
boston.target[1]

21.600000000000001

In [45]:
X = boston.data
y = boston.target
X = X[y<50.0]
y = y[y<50.0]

In [52]:
X.shape

(490, 13)

In [11]:
y.shape

(490,)

In [66]:
%run D:/Python1/KNN/model_selection.py

In [67]:
X_train,y_train,X_test,y_test = train_test_split(X,y,seed=666)

In [68]:
%run D:/Python1/Muke_MLB/LinearRegression.py

In [69]:
reg = LinearRegression()

In [70]:
reg.fit_normal(X_train,y_train)

LinearRegression

In [71]:
reg.coef_

array([ -1.18919477e-01,   3.63991462e-02,  -3.56494193e-02,
         5.66737830e-02,  -1.16195486e+01,   3.42022185e+00,
        -2.31470282e-02,  -1.19509560e+00,   2.59339091e-01,
        -1.40112724e-02,  -8.36521175e-01,   7.92283639e-03,
        -3.81966137e-01])

In [73]:
reg.intercept_

array([ 34.1614355])

In [51]:
reg.r2_score(X_test,y_test)

0.81298026026585368